### ISSUE TITLE
Code style for phpdoc

### ISSUE THREAD

**Issue by kesselb** [nextcloud/coding-standard#21]
The code style is documented https://docs.nextcloud.com/server/latest/developer_manual/getting_started/codingguidelines.html#comments but not checked with php-cs-fixer. 

Possible rules:

| Rule | Affected files in server |
|--------|--------|
| [`phpdoc_single_line_var_spacing => true`](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/930dc93a1b90eb991d13e2766a340aa6922d4a2c/doc/rules/phpdoc/phpdoc_single_line_var_spacing.rst) | 153 |
| [`'phpdoc_align' => ['align' => 'left']`](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/930dc93a1b90eb991d13e2766a340aa6922d4a2c/doc/rules/phpdoc/phpdoc_align.rst) | 205 |

What about git blame?

https://docs.github.com/en/repositories/working-with-files/using-files/viewing-a-file#ignore-commits-in-the-blame-view

**Comment by nickvergessen** [comment]
both sound good to me
