### ISSUE TITLE
Rule proposal `single_quote`

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/coding-standard#23]
Ref https://cs.symfony.com/doc/rules/string_notation/single_quote.html

I'd like to introduce it with the default value:
```diff
--- Original
+++ New
 <?php

-$a = "sample";
+$a = 'sample';
 $b = "sample with 'single-quotes'";
```

**Comment by ChristophWurst** [comment]
What happens to string with variables like `"hello $name"`?

**Comment by nickvergessen** [comment]
It's good:
![grafik](https://github.com/user-attachments/assets/0438a1bd-0d0b-48a3-aceb-5b1247621274)

Same for `\n`:
![grafik](https://github.com/user-attachments/assets/33b0965f-5ea5-47f8-8f71-e006a94a20c5)

**Comment by ChristophWurst** [comment]
Then :+1: fine by me
