### ISSUE TITLE
Rule proposal nullable_type_declaration

### ISSUE THREAD

**Issue by kesselb** [nextcloud/coding-standard#29]
https://cs.symfony.com/doc/rules/language_construct/nullable_type_declaration.html

Changes `DateTimeInterface|null` to `?DateTimeInterface`

`'nullable_type_declaration' => ['syntax' => 'question_mark'],`

25 files in server affected

**Comment by nickvergessen** [comment]
How does it handled `string|int|bool|null` ?

**Comment by nickvergessen** [comment]
Then I'm fine with the rule!
